package com.cts.training.mavenweb.dao;

import java.util.List;

import javax.transaction.Transactional;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.query.Query;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.cts.training.mavenweb.entity.Student;

@Repository
@Transactional
public class StudentDaoHibernateImpl implements IStudentDao {

	// dependency
	private SessionFactory sessionFactory;
	
	@Autowired
	public StudentDaoHibernateImpl(SessionFactory sessionFactory) {
		// TODO Auto-generated constructor stub
		this.sessionFactory = sessionFactory;
	}
	
	@Override
	public List<Student> findAll() {
		// TODO Auto-generated method stub
		// get the Hibernate Session object (Persistant Context)
		Session session = this.sessionFactory.getCurrentSession();
		
		
		// Student : entity class name
		// query generated by Hibernate is returned as Object
		Query<Student> query =  session.createQuery("from Student", Student.class);
		List<Student> students = query.getResultList();
		return students;
	}

	@Override
	public Student findById(Integer id) {
		// TODO Auto-generated method stub
		// get the Hibernate Session object (Persistant Context)
		// every time new session object is required
		// as persistant context works within a method
		Session session = this.sessionFactory.getCurrentSession();
		Student student = session.find(Student.class, id);
		
		return student;
	}

	@Override
	public boolean add(Student student) {
		// TODO Auto-generated method stub
		Session session = this.sessionFactory.getCurrentSession();
		
		session.save(student);
		
		return true;
	}

	@Override
	public boolean update(Student student) {
		// TODO Auto-generated method stub
		Session session = this.sessionFactory.getCurrentSession();
		
		session.update(student);
		return true;
	}

	@Override
	public boolean delete(Integer id) {
		// TODO Auto-generated method stub
		Session session = this.sessionFactory.getCurrentSession();
		
		session.remove(this.findById(id));
		return true;
	}

}
